theme: jekyll-theme-minimal
title: Snipe Predictor
description: Sniping


lsi: false
safe: true
source: git
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
